### PR TITLE
New model 

### PR DESCRIPTION
**Pull request by idkcollab312**
Made for Roblox games.

Dont know if this is a model that people will find useful but i made it.

Will work well with game Phantom Forces and should work with any similar game but didnt try.

### CODE REVIEW

**Review by Qfc9 — CHANGES_REQUESTED** [review]
Don't remove the readme.md file from the `exampleUsername` folder

**Comment by Qfc9** [comment]
What is your discord name? You will receive the Champion role once this PR is accepted.
YOU are in charge of updating this model and answering any questions people have about it.

**Comment by idkcollab312** [comment]
> trollatko#0221

**Comment by Qfc9** [comment]
Reminder

**Comment by idkcollab312** [comment]
Im very new to github and even after googling i have no idea how to edit a pull request will someone help please?

**Comment by Qfc9** [comment]
That is fine. Just make a new one from scratch. That would be easiest

**Comment by Qfc9** [comment]
Or you know what, ill just fix it

**Review by Qfc9 — APPROVED** [review]

**Pull request merged**
