### PR TITLE
Fix some typos

### PR DESCRIPTION
**Pull request by mrs1669**
1. enviroment -> enviro `n` ment
2. min `tu` es -> minutes
3. insted -> inste `a` d
4. satu `a` ration -> saturation
5. simultaneousy -> simultaneous `l` y
6. cammand -> c `o` mmand

### CODE REVIEW

**Comment by Qfc9** [comment]
Ok

**Comment by Niamxdks** [comment]
Hi

**Comment by Niamxdks** [comment]
Hello

**Comment by enriquesalazar-smith30-ux** [comment]
I really want to use your Aimbot

**Comment by ionygloria-create** [comment]
HOW TO USE IT?

**Pull request merged**
